theme: jekyll-theme-time-machine
title: KGQA by VA
description: A single page website presenting an automatic approach to generate Virtual Assistant (VA) extensions behaving as Knowledge Graphs (KGs) Question-answering (QA) systems.
github:
  zip_url: https://doi.org/10.5281/zenodo.4605951
  repository_url: https://github.com/mariaangelapellegrino/virtual_assistant_generator
